import '../../models/product_model.dart';

class MockProducts {
  static List<ProductModel> getSampleProducts() {
    return [
      ProductModel(
        id: '1',
        name: 'Premium Wireless Headphones',
        description: 'High-quality wireless headphones with active noise cancellation and 30-hour battery life.',
        price: 299.99,
        originalPrice: 399.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
        ],
        category: 'Electronics',
        brand: 'AudioTech',
        stock: 50,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.5, count: 234),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '2',
        name: 'Smart Watch Pro',
        description: 'Advanced fitness tracking with heart rate monitor, GPS, and waterproof design.',
        price: 449.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
        ],
        category: 'Electronics',
        brand: 'TechGear',
        stock: 30,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.7, count: 456),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '3',
        name: 'Designer Leather Bag',
        description: 'Handcrafted genuine leather bag with multiple compartments and adjustable strap.',
        price: 199.99,
        originalPrice: 299.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500',
        ],
        category: 'Fashion',
        brand: 'LuxStyle',
        stock: 25,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.3, count: 89),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '4',
        name: 'Casual Cotton T-Shirt',
        description: 'Comfortable 100% cotton t-shirt available in multiple colors and sizes.',
        price: 49.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        ],
        category: 'Fashion',
        brand: 'ComfortWear',
        stock: 100,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.2, count: 567),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '5',
        name: 'Modern Table Lamp',
        description: 'Elegant LED table lamp with touch control and adjustable brightness.',
        price: 89.99,
        originalPrice: 129.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
        ],
        category: 'Home',
        brand: 'HomeLight',
        stock: 40,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.6, count: 123),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '6',
        name: 'Cozy Throw Blanket',
        description: 'Soft and warm fleece blanket perfect for cozy evenings. Machine washable.',
        price: 69.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
        ],
        category: 'Home',
        brand: 'CozyHome',
        stock: 60,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.8, count: 234),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '7',
        name: 'Organic Face Serum',
        description: 'Anti-aging serum with natural ingredients, suitable for all skin types.',
        price: 79.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500',
        ],
        category: 'Beauty',
        brand: 'PureBeauty',
        stock: 35,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.4, count: 178),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '8',
        name: 'Professional Makeup Brush Set',
        description: 'Complete 12-piece brush set with premium synthetic bristles and travel case.',
        price: 129.99,
        originalPrice: 179.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500',
        ],
        category: 'Beauty',
        brand: 'GlamPro',
        stock: 20,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.9, count: 345),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '9',
        name: 'Wireless Bluetooth Speaker',
        description: '360-degree sound with deep bass, 12-hour playtime, and IPX7 waterproof rating.',
        price: 149.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
        ],
        category: 'Electronics',
        brand: 'SoundWave',
        stock: 45,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.6, count: 289),
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '10',
        name: 'Running Shoes',
        description: 'Lightweight athletic shoes with cushioned sole and breathable mesh upper.',
        price: 179.99,
        originalPrice: 229.99,
        currency: 'AED',
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        ],
        category: 'Fashion',
        brand: 'SportFit',
        stock: 55,
        isForMobile: true,
        isActive: true,
        rating: ProductRating(average: 4.5, count: 678),
        createdAt: DateTime.now(),
      ),
    ];
  }
}
